spring.application.name=number-generator
server.port=8081

# Connection
spring.data.redis.host=192.168.0.13
spring.data.redis.port=6379

# Connection pool tuning
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=0
spring.data.redis.lettuce.pool.time-between-eviction-runs=10s
